### ISSUE TITLE
will it be available for opencv3? or it just dies?

### ISSUE THREAD

**Issue by autosquid** [sinelaw/HOpenCV#11]
I am looking for a haskell binding but with no good result. Is this binding dead?

**Comment by sinelaw** [comment]
I'll look into supporting OpenCV 3. Is there any missing API you need or just the existing supported functions but with underlying OpenCV 3?

**Comment by autosquid** [comment]
opencv3 added many new features, such as
new line descriptors, KAZE/AKAZE and 2d shape matching module and 3d surface matching module.

I had opencv3 installed on my mac due to these new stuff.

Thanks for your work.

**Comment by sinelaw** [comment]
I have no plans to add new functionality at the moment. If what you want is
to just be able to run against OpenCV 3 then I can help.
